export const MOCK_USERS = [
  {
    user_id: 1,
    account_id: 101,
    first_name: "ธนธรณ์",
    last_name: "ธนภาสภากร",
    sex: "ชาย",
    email: "thanathorn@email.com",
    phone: "0812345678",
    role: "Patient",
  },
  {
    user_id: 2,
    account_id: 102,
    first_name: "สมหญิง",
    last_name: "ใจดีมาก",
    sex: "หญิง",
    email: "somying@email.com",
    phone: "0822222222",
    role: "Patient",
  },
  {
    user_id: 3,
    account_id: 103,
    first_name: "มานะ",
    last_name: "อดทนยิ่ง",
    sex: "ชาย",
    email: "mana@email.com",
    phone: "0833333333",
    role: "Patient",
  },
  {
    user_id: 4,
    account_id: 104,
    first_name: "กนกวรรณ",
    last_name: "ขยันเรียน",
    sex: "หญิง",
    email: "kanok@email.com",
    phone: "0844444444",
    role: "Patient",
  },
  {
    user_id: 5,
    account_id: 105,
    first_name: "สมชาย",
    last_name: "หมายมั่น",
    sex: "ชาย",
    email: "somchai@email.com",
    phone: "0855555555",
    role: "Patient",
  },
];

export const MOCK_DOCTOR = [
  {
    doctor_id: 201,
    account_id: 201,
    first_name: "นพ.รักษา",
    last_name: "ยาดี",
    sex: "ชาย",
    email: "luxsa@email.com",
    phone: "0825019888",
    role: "Doctor",
    employee_id: "DOC101",
    position: "General Practitioner",
    license_no: "DT111",
  },
  {
    doctor_id: 202,
    account_id: 202,
    first_name: "พญ.ใจดี",
    last_name: "มีเมตตา",
    sex: "หญิง",
    email: "jaidee@email.com",
    phone: "0812345678",
    role: "Doctor",
    employee_id: "DOC102",
    position: "Pediatrician",
    license_no: "DT222",
  },
  {
    doctor_id: 203,
    account_id: 203,
    first_name: "นพ.สมเกียรติ",
    last_name: "มือทอง",
    sex: "ชาย",
    email: "somkiat@email.com",
    phone: "0898765432",
    role: "Doctor",
    employee_id: "DOC103",
    position: "Surgeon",
    license_no: "DT333",
  },
];

export const MOCK_NURSE = [
  {
    nurse_id: 301,
    account_id: 301,
    first_name: "พยาบาลสมหญิง",
    last_name: "มือเบา",
    sex: "หญิง",
    email: "somying@email.com",
    phone: "0833334444",
    role: "Nurse",
    employee_id: "NUR101",
    position: "Head Nurse",
    nursing_license: "RN999",
  },
];

// จำลองข้อมูลจากตาราง Queue + Join กับข้อมูล Doctor
export const MOCK_QUEUES = [
  {
    queue_id: 1001,
    user_id: 2,
    schedule_id: 502,
    queue_no: "A101",
    first_name: "สมหญิง",
    last_name: "ใจดีมาก",
    symptoms_initial: "ปวดท้องบิดๆ",
    status: "completed",
    booked_at: "2023-10-27T08:30:00",
    waiting_count: 0,
    doctor_name: "นพ.รักษา ยาดี",
    doctor_id: 201,
  },
  {
    queue_id: 1002,
    user_id: 1,
    schedule_id: 502,
    queue_no: "A102",
    first_name: "ธนธรณ์",
    last_name: "ธนภาสภากร",
    symptoms_initial: "ปวดหัว ตัวร้อน",
    status: "examining",
    booked_at: "2023-10-27T09:30:00",
    waiting_count: 0,
    doctor_name: "นพ.รักษา ยาดี",
    doctor_id: 201,
  },
  {
    queue_id: 1003,
    user_id: 3,
    schedule_id: 502,
    queue_no: "A103",
    first_name: "มานะ",
    last_name: "อดทนยิ่ง",
    symptoms_initial: "มีไข้สูง หนาวสั่น",
    status: "screening",
    booked_at: "2023-10-27T09:45:00",
    waiting_count: 1,
    doctor_name: "นพ.รักษา ยาดี",
    doctor_id: 201,
  },
  {
    queue_id: 1004,
    user_id: 4,
    schedule_id: 502,
    queue_no: "A104",
    first_name: "กนกวรรณ",
    last_name: "ขยันเรียน",
    symptoms_initial: "ผื่นแดงตามตัว",
    status: "waiting",
    booked_at: "2023-10-27T10:00:00",
    waiting_count: 2,
    doctor_name: "นพ.รักษา ยาดี",
  },
  {
    queue_id: 1005,
    user_id: 5,
    schedule_id: 502,
    queue_no: "A105",
    first_name: "สมชาย",
    last_name: "หมายมั่น",
    symptoms_initial: "ไอแห้ง เจ็บคอ",
    status: "waiting",
    booked_at: "2023-10-27T10:15:00",
    waiting_count: 3,
    doctor_name: "นพ.รักษา ยาดี",
  },
];

export const MOCK_SCHEDULES = [
  {
    schedule_id: 501,
    doctor_id: 201,
    doctor_name: "นพ.รักษา ยาดี", // Join มาจาก User
    date: "2023-10-27",
    start_time: "09:00",
    end_time: "10:00",
    room_no: "1",
    max_patients: 5,
    current_count: 5,
    is_available: true,
  },
  {
    schedule_id: 502,
    doctor_id: 201,
    doctor_name: "นพ.รักษา ยาดี",
    date: "2023-10-27",
    start_time: "10:00",
    end_time: "11:00",
    room_no: "1",
    max_patients: 5,
    current_count: 4,
    is_available: true,
  },
  {
    schedule_id: 503,
    doctor_id: 201,
    doctor_name: "นพ.รักษา ยาดี",
    date: "2023-10-27",
    start_time: "11:00",
    end_time: "12:00",
    room_no: "1",
    max_patients: 5,
    current_count: 0,
    is_available: false,
  },
  {
    schedule_id: 504,
    doctor_id: 201,
    doctor_name: "นพ.รักษา ยาดี",
    date: "2023-10-27",
    start_time: "12:00",
    end_time: "13:00",
    room_no: "1",
    max_patients: 5,
    current_count: 1,
    is_available: true, 
  },
  {
    schedule_id: 505,
    doctor_id: 201,
    doctor_name: "นพ.รักษา ยาดี",
    date: "2023-10-27",
    start_time: "13:00",
    end_time: "14:00",
    room_no: "1",
    max_patients: 5,
    current_count: 2,
    is_available: true,
  },
  {
    schedule_id: 506,
    doctor_id: 201,
    doctor_name: "นพ.รักษา ยาดี",
    date: "2023-10-27",
    start_time: "14:00",
    end_time: "15:00",
    room_no: "1",
    max_patients: 5,
    current_count: 0,
    is_available: true, 
  },
];
